import assert from "node:assert/strict";
import test from "node:test";
import { FarViewCore } from "../src/core/far-view.js";
import { BoundedPriorityScheduler, priorityForDistance } from "../src/core/performance.js";
import { GameplayPressureTracker, PlayabilityShield } from "../src/core/playability.js";
import { AdaptivePerformanceGovernor } from "../src/core/governor.js";
import {
  AxeAdapter,
  BowAdapter,
  CooldownResolver,
  CriticalResolver,
  CustomWeaponAdapter,
  DamageResolver,
  KnockbackResolver,
  SpearAdapter,
  SwordAdapter,
  UniversalAttackAPI,
  WeaponRegistry,
  type CombatExecutionPort,
  type WeaponAdapter,
  type WeaponDefinition,
} from "../src/core/combat.js";
import type { WorkItem } from "../src/core/types.js";

const weapon = (id: string, attackType: WeaponDefinition["attackType"]): WeaponDefinition => ({ id, attackType, baseDamage: 10, range: 3, cooldownTicks: 5, knockback: 2, durabilityCost: 1 });
const makeApi = () => new UniversalAttackAPI(new CooldownResolver(), new CriticalResolver(), new DamageResolver(), new KnockbackResolver());
const makePort = (targetDistance = 2, calls: string[] = []): CombatExecutionPort => ({ resolveTarget: () => { calls.push("resolve"); return { id: "t", entity: {}, distance: targetDistance }; }, applyDamage: (_target, damage) => { calls.push(`damage:${damage}`); return true; }, applyKnockback: (_target, impulse) => { calls.push(`knockback:${impulse.x}`); } });
const context = { attackerId: "a", targetId: "t", direction: { x: 1, y: 0, z: 0 }, tick: 10, criticalEligible: false };

test("far-view first observation preserves lifecycle even when initially distant", () => { const core = new FarViewCore(); const decision = core.observeDistance("c", 70, 1); assert.equal(decision.zone, "64-100"); assert.equal(core.getState("c"), "FAR"); });
test("far-view lifecycle supports recovery and release", () => { const core = new FarViewCore(); core.observeDistance("c", 4, 1); assert.equal(core.getState("c"), "VISIBLE"); core.observeDistance("c", 70, 2); assert.equal(core.getState("c"), "FAR"); core.observeDistance("c", 20, 3); assert.equal(core.getState("c"), "VISIBLE"); core.release("c", 4); assert.equal(core.getState("c"), "RELEASED"); core.clearReleased(); assert.equal(core.getState("c"), undefined); });
test("far-view invalid transitions are rejected", () => { const core = new FarViewCore(); assert.equal(core.transition("bad", "FAR", 1), false); assert.equal(core.transition("bad", "DISCOVERED", 1), true); assert.equal(core.transition("bad", "FAR", 2), false); assert.equal(core.transition("bad", "VISIBLE", 2), true); });
test("far-view boundaries and invalid distances", () => { const core = new FarViewCore(); for (const [value, zone] of [[0,"0-8"],[8,"8-16"],[16,"16-32"],[32,"32-64"],[64,"64-100"],[100,"64-100"]] as const) assert.equal(core.classifyChunkDistance(value).zone, zone); for (const value of [100.001,-1,Number.NaN,Number.POSITIVE_INFINITY]) assert.equal(core.classifyChunkDistance(value).zone,"OUT_OF_RANGE"); });
test("distance zones map to authoritative scheduler priorities", () => { assert.equal(priorityForDistance("0-8"), "CRITICAL"); assert.equal(priorityForDistance("8-16"), "NEAR"); assert.equal(priorityForDistance("16-32"), "IMPORTANT"); assert.equal(priorityForDistance("32-64"), "MID"); assert.equal(priorityForDistance("64-100"), "FAR"); const scheduler = new BoundedPriorityScheduler<void>({ maxQueue: 8, maxPerWindow: 8 }); scheduler.enqueue({ key: "32-64", priority: "MID", createdAtTick: 1, payload: undefined }); scheduler.enqueue({ key: "64-100", priority: "FAR", createdAtTick: 1, payload: undefined }); assert.equal(scheduler.peekPriority("32-64"), "MID"); assert.equal(scheduler.peekPriority("64-100"), "FAR"); });
test("bounded priority scheduler protects high priority", () => { const scheduler = new BoundedPriorityScheduler<number>({ maxQueue: 2, maxPerWindow: 1 }); const item = (key: string, priority: WorkItem<number>["priority"]): WorkItem<number> => ({ key, priority, createdAtTick: 1, payload: 1 }); assert.equal(scheduler.enqueue(item("low", "FAR")), true); assert.equal(scheduler.enqueue(item("decorative", "DECORATIVE")), true); assert.equal(scheduler.enqueue(item("critical", "CRITICAL")), true); let ran = 0; scheduler.drain(() => ran++); assert.equal(ran, 1); });
test("gameplay pressure blocks far/decorative work and expires", () => { const pressure = new GameplayPressureTracker(3); const shield = new PlayabilityShield(pressure); pressure.mark("COMBAT", 0); assert.equal(shield.shouldDegrade("FAR", 1), true); assert.equal(shield.shouldDegrade("DECORATIVE", 1), true); assert.equal(shield.shouldDegrade("COMBAT", 1), false); assert.equal(shield.shouldDegrade("FAR", 4), false); assert.equal(shield.priorityFor("CAMERA"), "CRITICAL"); assert.equal(shield.priorityFor("BOSS"), "CRITICAL"); });
test("governor changes executable policy under pressure", () => { const governor = new AdaptivePerformanceGovernor(); assert.equal(governor.evaluate({ queueRatio: 1, workRatio: 1, memoryRatio: 0, localGameplayActive: true }), "CRITICAL"); assert.equal(governor.workloadPolicy().allowFar, false); assert.equal(governor.workloadPolicy().allowDecorative, false); assert.equal(governor.workloadPolicy().executionBudget, 2); });
test("all five adapters converge and all seven attack types reach central resolver", () => { const adapters: WeaponAdapter[] = [new SwordAdapter(weapon("sword","MELEE")),new AxeAdapter(weapon("axe","HEAVY_MELEE")),new SpearAdapter(weapon("spear","THRUST")),new BowAdapter(weapon("bow","RANGED")),new CustomWeaponAdapter(weapon("custom","SPECIAL"))]; const allTypes: WeaponDefinition["attackType"][] = ["MELEE","HEAVY_MELEE","THRUST","SWEEP","RANGED","PROJECTILE","SPECIAL"]; const api = makeApi(); const calls: string[] = []; for (const [index, attackType] of allTypes.entries()) { const adapter = attackType === "MELEE" ? adapters[0] : attackType === "HEAVY_MELEE" ? adapters[1] : attackType === "THRUST" ? adapters[2] : attackType === "RANGED" ? adapters[3] : new CustomWeaponAdapter(weapon(`custom-${index}`, attackType)); assert.ok(adapter); assert.equal(api.executeAdapter(adapter, { ...context, tick: 20 + index }, makePort(2,calls)).accepted, true); } assert.equal(api.weapons.size, 7); assert.equal(calls.filter(call => call === "resolve").length, 7); });
test("weapon validation rejects unregistered and mismatched requests", () => { const registry = new WeaponRegistry(); const api = new UniversalAttackAPI(new CooldownResolver(),new CriticalResolver(),new DamageResolver(),new KnockbackResolver(),registry); const request = new SwordAdapter(weapon("sword","MELEE")).toAttackRequest(context); assert.equal(api.execute(request,makePort()).reason,"WEAPON_UNREGISTERED"); assert.equal(registry.register(weapon("sword","MELEE")),true); assert.equal(api.execute({ ...request, attackType: "PROJECTILE" }, makePort()).reason,"WEAPON_ATTACK_TYPE_MISMATCH"); });
test("central pipeline keeps base modified final damage distinct and resolves target once", () => { const api = makeApi(); const adapter = new SwordAdapter({ ...weapon("sword","MELEE"), modifiers:[{id:"strength",multiplier:2}] }); const calls:string[]=[]; const port:CombatExecutionPort={...makePort(2,calls),mitigateArmorDamage:(_t,_r,incoming)=>incoming-3,mitigateResistanceDamage:(_t,_r,incoming)=>incoming-2,applyDurability:(_r)=>true}; const result=api.executeAdapter(adapter,{...context,criticalEligible:true},port); assert.equal(result.accepted,true); assert.equal(result.baseDamage,10); assert.equal(result.modifiedDamage,30); assert.equal(result.finalDamage,25); assert.equal(result.armorStatus,"VERIFIED"); assert.equal(result.resistanceStatus,"VERIFIED"); assert.equal(result.durabilityStatus,"VERIFIED"); assert.equal(calls.filter(call=>call==="resolve").length,1); });
test("armor and resistance statuses are independent", () => { const api=makeApi(); const adapter=new SwordAdapter(weapon("sword","MELEE")); const result=api.executeAdapter(adapter,context,{...makePort(),mitigateArmorDamage:(_t,_r,incoming)=>incoming-1}); assert.equal(result.armorStatus,"VERIFIED"); assert.equal(result.resistanceStatus,"NOT_VERIFIED"); });
test("unsupported later stages remain explicitly unverified without runtime capability", () => { const api=makeApi(); const adapter=new BowAdapter({...weapon("bow","PROJECTILE"),effects:[{id:"slowness",durationTicks:20,amplifier:1}]}); const result=api.executeAdapter(adapter,context,makePort()); assert.equal(result.durabilityStatus,"NOT_VERIFIED"); assert.deepEqual(result.effectStatuses,["NOT_VERIFIED"]); assert.equal(result.projectileStatus,"NOT_VERIFIED"); assert.equal(result.deathStatus,"NOT_VERIFIED"); assert.equal(result.lootStatus,"NOT_VERIFIED"); assert.equal(result.xpStatus,"NOT_VERIFIED"); });
test("range and target validation reject before mutation", () => { const api=makeApi(); const request=new SwordAdapter(weapon("sword","MELEE")).toAttackRequest(context); assert.equal(api.weapons.register(weapon("sword","MELEE")),true); const port:CombatExecutionPort={resolveTarget:()=>({id:"wrong",entity:{},distance:1}),applyDamage:()=>{throw new Error("damage must not run")},applyKnockback:()=>{throw new Error("knockback must not run")}}; assert.equal(api.execute(request,port).reason,"TARGET_INVALID"); const outOfRange={...port,resolveTarget:()=>({id:"t",entity:{},distance:4})}; assert.equal(api.execute(request,outOfRange).reason,"OUT_OF_RANGE"); });
test("cooldown blocks second attack", () => { const api=makeApi(); const adapter=new SwordAdapter(weapon("sword","MELEE")); assert.equal(api.executeAdapter(adapter,context,makePort()).accepted,true); assert.equal(api.executeAdapter(adapter,{...context,tick:11},makePort()).reason,"COOLDOWN"); });
